server:
  port: 8090
spring:
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery: SERVICE-CAR
  application:
    name: SERVICE-CAR
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/carservicedb?createDatabaseIfNotExist=true
    username: "root"
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

